# Generated by Django 4.2.28 on 2026-02-28 14:36

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='blood_group',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('0+', 'I Rh+'), ('0-', 'I Rh-'), ('A+', 'II Rh+'), ('A-', 'II Rh-'), ('B+', 'III Rh+'), ('B-', 'III Rh-'), ('AB+', 'IV Rh+'), ('AB-', 'IV Rh-')], default='', max_length=100)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('0+', 'I Rh+'), ('0-', 'I Rh-'), ('A+', 'II Rh+'), ('A-', 'II Rh-'), ('B+', 'III Rh+'), ('B-', 'III Rh-'), ('AB+', 'IV Rh+'), ('AB-', 'IV Rh-')], default='', max_length=100)),
            preserve_default=False,
        ),
    ]
