# Generated by Django 4.2.28 on 2026-02-28 15:33

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_historicalpatient_blood_group_patient_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='blood_group',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('I Rh+', 'I Rh+'), ('I Rh-', 'I Rh-'), ('II Rh+', 'II Rh+'), ('II Rh-', 'II Rh-'), ('III Rh+', 'III Rh+'), ('III Rh-', 'III Rh-'), ('IV Rh+', 'IV Rh+'), ('IV Rh-', 'IV Rh-')], max_length=100)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('I Rh+', 'I Rh+'), ('I Rh-', 'I Rh-'), ('II Rh+', 'II Rh+'), ('II Rh-', 'II Rh-'), ('III Rh+', 'III Rh+'), ('III Rh-', 'III Rh-'), ('IV Rh+', 'IV Rh+'), ('IV Rh-', 'IV Rh-')], max_length=100)),
        ),
    ]
