# Generated by Django 6.0.2 on 2026-03-07 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_historicalpatient_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmedical_history',
            name='date_arrival',
        ),
        migrations.RemoveField(
            model_name='historicalmedical_history',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='historicalprescribed_analysis',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='historicalprescribed_analysis',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='historicalprescribed_medicine',
            name='date_prescribed',
        ),
        migrations.RemoveField(
            model_name='historicalprescribed_medicine',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='historicalprescribed_medicine',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medical_history',
            name='date_arrival',
        ),
        migrations.RemoveField(
            model_name='medical_history',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescribed_analysis',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescribed_analysis',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescribed_medicine',
            name='date_prescribed',
        ),
        migrations.RemoveField(
            model_name='prescribed_medicine',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescribed_medicine',
            name='patient',
        ),
        migrations.AddField(
            model_name='historicalmedical_history',
            name='prescribed_service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.prescribed_service'),
        ),
        migrations.AddField(
            model_name='historicalprescribed_analysis',
            name='medical_history',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.medical_history'),
        ),
        migrations.AddField(
            model_name='historicalprescribed_medicine',
            name='medical_history',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.medical_history'),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='prescribed_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prescribed_service'),
        ),
        migrations.AddField(
            model_name='prescribed_analysis',
            name='medical_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.medical_history'),
        ),
        migrations.AddField(
            model_name='prescribed_medicine',
            name='medical_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.medical_history'),
        ),
        migrations.AlterField(
            model_name='analysis_guide',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diagnosis_guide',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalmedical_history',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalposition',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalprescribed_analysis',
            name='date_prescribed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalprescribed_analysis',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalprescribed_medicine',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalprescribed_service',
            name='date_prescribed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalprescribed_service',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalresponse',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicine_guide',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='position_service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prescribed_analysis',
            name='date_prescribed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prescribed_analysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prescribed_medicine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prescribed_service',
            name='date_prescribed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prescribed_service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service_guide',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='work_schedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='position_service',
            unique_together={('position', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='work_schedule',
            unique_together={('employee', 'day_of_week')},
        ),
    ]
