# Generated by Django 6.0.2 on 2026-03-15 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_historicalmedical_history_date_arrival_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalposition',
            name='code',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.code'),
        ),
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.code'),
        ),
    ]
