# Generated by Django 6.0.2 on 2026-04-04 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_code_alter_historicalposition_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_history',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.diagnosis_guide'),
        ),
    ]
