# Generated by Django 6.0.2 on 2026-05-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_medical_history_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprescribed_service',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescribed_service',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
